# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/57ce2148-d18e-4e00-88f4-f3ead4843936";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=lzo" "ssd" "discard" "space_cache" "subvol=@nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/57ce2148-d18e-4e00-88f4-f3ead4843936";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=lzo" "ssd" "discard" "space_cache" "subvol=@nixos-home" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/57ce2148-d18e-4e00-88f4-f3ead4843936";
      fsType = "btrfs";
      options = [ "rw" "noatime" "compress=lzo" "ssd" "discard" "space_cache" "subvol=@nixos-home-snaps" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8709-ED44";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f5d6e6fd-3a53-4d74-8cd9-a480e5e09610"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
