#! /bin/sh
sxhkd &
polybar -r example &
tmux -2 new-session -d -s irc weechat &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           24
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty -o desktop='^5' state=tiled && alacritty -e tmux attach -t irc &
bspc rule -a Nightly desktop='^2' state=tiling follow=on
bspc rule -a Emacs desktop='^1' state=tiling follow=on
bspc rule -a Alacritty desktop='^3' state=tiling follow=on
bspc rule -a Spotify desktop='^4' state=pseudo_tiled follow=on
bspc rule -a Thunar pseudo_tiled=on
